terraform {
  required_providers {
    coder = {
      source = "coder/coder"
    }
  }
}

variable "agent_id" {
  type        = string
  description = "The ID of a Coder agent."
}

variable "external_auth_id" {
  type        = string
  description = "The Coder external auth provider ID (e.g. 'primary-github') used to fetch fresh OAuth tokens at runtime."
}

data "coder_parameter" "install_github_cli" {
  name         = "install_github_cli"
  display_name = "GitHub CLI"
  description  = "Install the official GitHub CLI (gh) and auto-authenticate it with Coder's GitHub OAuth token"
  default      = true
  type         = "bool"
  mutable      = true
  icon         = "https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/github.svg"
}

resource "coder_script" "github_tools" {
  agent_id     = var.agent_id
  display_name = "Install GitHub CLI"
  icon         = "https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/github.svg"
  run_on_start = true
  script       = <<EOT
#!/bin/bash
set -e

if [ "${data.coder_parameter.install_github_cli.value}" = "true" ]; then
  GH_BIN="/usr/local/bin/gh-bin"
  GH_WRAPPER="/usr/local/bin/gh"
  AUTH_ID="${var.external_auth_id}"

  # --- Install gh CLI binary if not present ---
  if [ ! -f "$GH_BIN" ]; then
    echo "Installing GitHub CLI..."
    GH_VERSION=$(curl -sI https://github.com/cli/cli/releases/latest | awk -F/ '/^location:/ || /^Location:/ {print $NF}' | tr -d '\r' | sed 's/^v//')
    curl -fsSL "https://github.com/cli/cli/releases/download/v$${GH_VERSION}/gh_$${GH_VERSION}_linux_amd64.tar.gz" | tar xz -C /tmp
    sudo mv "/tmp/gh_$${GH_VERSION}_linux_amd64/bin/gh" "$GH_BIN"
    sudo chmod +x "$GH_BIN"
  fi

  # --- Create wrapper script that dynamically fetches a fresh token ---
  # This replaces the real 'gh' binary path so it works in ANY shell
  # (login shell, non-login shell, scripts, cron, etc.)
  # without depending on .bashrc being sourced.
  sudo tee "$GH_WRAPPER" > /dev/null << WRAPPER
#!/bin/bash
# Auto-generated by Coder github-tools module
# Fetches a fresh GitHub OAuth token on every invocation via Coder external auth.
TOKEN=\$(command coder external-auth access-token $${AUTH_ID} 2>/dev/null)
if [ -n "\$TOKEN" ]; then
  export GITHUB_TOKEN="\$TOKEN"
fi
exec $GH_BIN "\$@"
WRAPPER
  sudo chmod +x "$GH_WRAPPER"

  # --- Clean up stale GITHUB_TOKEN from .bashrc if present ---
  BASHRC="$${HOME}/.bashrc"
  if grep -qF "# coder-gh-dynamic-token" "$BASHRC" 2>/dev/null; then
    # Remove the old function-based wrapper from previous template versions
    sed -i '/# coder-gh-dynamic-token/,/# end-coder-gh-dynamic-token/d' "$BASHRC"
    # Also clean up any standalone unset lines left from earlier versions
    sed -i '/^unset GITHUB_TOKEN 2>\/dev\/null$/d' "$BASHRC"
    echo "🧹 Cleaned up old .bashrc gh wrapper."
  fi

  echo "✅ GitHub CLI installed with dynamic token refresh (auth: $${AUTH_ID})."
fi
EOT
}
